const dadosTickets = [
    {
        numeroTicket: '430',
        nomeCompleto: 'Lucas E',
        status: 'Em Andamento',
        abertura: '15/08/2024 15:29:33',
        dataLimite: '',
        matricula: '12345',
        telefone: '11987654321',
        emailSolicitante: 'lucas.e@example.com',
        cargo: 'Analista de TI',
        areaNegocio: 'TI',
        hub: 'São Paulo',
        unidadeNegocio: 'SP - Sede',
        categoria: 'Categoria 1',
        subcategoria: 'Subcategoria 1',
        assunto: 'Assunto 1',
        descricao: 'Descrição do ticket 1',
        observacao: 'Observação do ticket 1',
        anexo: null,
        autorizacao: 'documento_autorizacao_430.pdf',
        equipe: 'TI',
    },
    {
        numeroTicket: '1001',
        nomeCompleto: 'Lucas E',
        status: 'Pendente',
        abertura: '15/08/2024 12:00:00',
        dataLimite: '',
        matricula: '12346',
        telefone: '11987654322',
        emailSolicitante: 'lucas.e@example.com',
        cargo: 'Analista de TI',
        areaNegocio: 'TI',
        hub: 'São Paulo',
        unidadeNegocio: 'SP - Sede',
        categoria: 'Categoria 2',
        subcategoria: 'Subcategoria 2',
        assunto: 'Assunto 2',
        descricao: 'Descrição do ticket 2',
        observacao: 'Observação do ticket 2',
        anexo: null,
        autorizacao: 'documento_autorizacao_1001.pdf',
        equipe: 'TI',
    },
    {
        numeroTicket: '1002',
        nomeCompleto: 'Lucas E',
        status: 'Concluido',
        abertura: '14/08/2024 09:00:00',
        dataLimite: '',
        matricula: '12347',
        telefone: '11987654323',
        emailSolicitante: 'lucas.e@example.com',
        cargo: 'Analista de TI',
        areaNegocio: 'TI',
        hub: 'São Paulo',
        unidadeNegocio: 'SP - Sede',
        categoria: 'Categoria 3',
        subcategoria: 'Subcategoria 3',
        assunto: 'Assunto 3',
        descricao: 'Descrição do ticket 3',
        observacao: 'Observação do ticket 3',
        anexo: null,
        autorizacao: 'documento_autorizacao_1002.pdf',
        equipe: 'TI',
    },
    {
        numeroTicket: '1003',
        nomeCompleto: 'Carlos Souza',
        status: 'Cancelado',
        abertura: '13/08/2024 10:30:00',
        dataLimite: '',
        matricula: '12348',
        telefone: '11987654324',
        emailSolicitante: 'carlos.s@example.com',
        cargo: 'Gestor de Projetos',
        areaNegocio: 'Governança',
        hub: 'Rio de Janeiro',
        unidadeNegocio: 'RJ - Filial',
        categoria: 'Categoria 4',
        subcategoria: 'Subcategoria 4',
        assunto: 'Assunto 4',
        descricao: 'Descrição do ticket 4',
        observacao: 'Observação do ticket 4',
        anexo: null,
        autorizacao: 'documento_autorizacao_1003.pdf',
        equipe: 'Governança',
    },
    {
        numeroTicket: '1004',
        nomeCompleto: 'Ana Paula',
        status: 'Em Andamento',
        abertura: '12/08/2024 14:20:00',
        dataLimite: '',
        matricula: '12349',
        telefone: '11987654325',
        emailSolicitante: 'ana.paula@example.com',
        cargo: 'Coordenadora',
        areaNegocio: 'MV',
        hub: 'Minas Gerais',
        unidadeNegocio: 'MG - Filial',
        categoria: 'Categoria 5',
        subcategoria: 'Subcategoria 5',
        assunto: 'Assunto 5',
        descricao: 'Descrição do ticket 5',
        observacao: 'Observação do ticket 5',
        anexo: null,
        autorizacao: 'documento_autorizacao_1004.pdf',
        equipe: 'MV',
    },
    {
        numeroTicket: '1005',
        nomeCompleto: 'Bruno Martins',
        status: 'Pendente',
        abertura: '11/08/2024 16:45:00',
        dataLimite: '',
        matricula: '12350',
        telefone: '11987654326',
        emailSolicitante: 'bruno.martins@example.com',
        cargo: 'Analista de Suporte',
        areaNegocio: 'TASY',
        hub: 'Bahia',
        unidadeNegocio: 'BA - Filial',
        categoria: 'Categoria 6',
        subcategoria: 'Subcategoria 6',
        assunto: 'Assunto 6',
        descricao: 'Descrição do ticket 6',
        observacao: 'Observação do ticket 6',
        anexo: null,
        autorizacao: 'documento_autorizacao_1005.pdf',
        equipe: 'TASY',
    },
    {
        numeroTicket: '1006',
        nomeCompleto: 'Fernanda Lima',
        status: 'Em Andamento',
        abertura: '10/08/2024 10:00:00',
        dataLimite: '',
        matricula: '12351',
        telefone: '11987654327',
        emailSolicitante: 'fernanda.lima@example.com',
        cargo: 'Analista de Sistemas',
        areaNegocio: 'SAP',
        hub: 'São Paulo',
        unidadeNegocio: 'SP - Filial',
        categoria: 'Categoria 7',
        subcategoria: 'Subcategoria 7',
        assunto: 'Assunto 7',
        descricao: 'Descrição do ticket 7',
        observacao: 'Observação do ticket 7',
        anexo: null,
        autorizacao: 'documento_autorizacao_1006.pdf',
        equipe: 'SAP',
    },
    {
        numeroTicket: '1007',
        nomeCompleto: 'Lucas E',
        status: 'Pendente',
        abertura: '09/08/2024 11:30:00',
        dataLimite: '',
        matricula: '12352',
        telefone: '11987654328',
        emailSolicitante: 'lucas.e@example.com',
        cargo: 'Analista de TI',
        areaNegocio: 'TI',
        hub: 'São Paulo',
        unidadeNegocio: 'SP - Sede',
        categoria: 'Categoria 8',
        subcategoria: 'Subcategoria 8',
        assunto: 'Assunto 8',
        descricao: 'Descrição do ticket 8',
        observacao: 'Observação do ticket 8',
        anexo: null,
        autorizacao: 'documento_autorizacao_1007.pdf',
        equipe: 'TI',
    },
    {
        numeroTicket: '1008',
        nomeCompleto: 'Mariana Azevedo',
        status: 'Em Andamento',
        abertura: '08/08/2024 09:15:00',
        dataLimite: '',
        matricula: '12353',
        telefone: '11987654329',
        emailSolicitante: 'mariana.azevedo@example.com',
        cargo: 'Coordenadora de Projetos',
        areaNegocio: 'TI',
        hub: 'São Paulo',
        unidadeNegocio: 'SP - Sede',
        categoria: 'Categoria 9',
        subcategoria: 'Subcategoria 9',
        assunto: 'Assunto 9',
        descricao: 'Descrição do ticket 9',
        observacao: 'Observação do ticket 9',
        anexo: null,
        autorizacao: 'documento_autorizacao_1008.pdf',
        equipe: 'TI',
    },
    {
        numeroTicket: '1009',
        nomeCompleto: 'Paulo Henrique',
        status: 'Concluido',
        abertura: '07/08/2024 08:45:00',
        dataLimite: '',
        matricula: '12354',
        telefone: '11987654330',
        emailSolicitante: 'paulo.henrique@example.com',
        cargo: 'Analista de Suporte',
        areaNegocio: 'TI',
        hub: 'São Paulo',
        unidadeNegocio: 'SP - Sede',
        categoria: 'Categoria 10',
        subcategoria: 'Subcategoria 10',
        assunto: 'Assunto 10',
        descricao: 'Descrição do ticket 10',
        observacao: 'Observação do ticket 10',
        anexo: null,
        autorizacao: 'documento_autorizacao_1009.pdf',
        equipe: 'TI',
    },
    {
        numeroTicket: '1010',
        nomeCompleto: 'Juliana Silva',
        status: 'Pendente',
        abertura: '06/08/2024 14:00:00',
        dataLimite: '',
        matricula: '12355',
        telefone: '11987654331',
        emailSolicitante: 'juliana.silva@example.com',
        cargo: 'Analista de TI',
        areaNegocio: 'TI',
        hub: 'São Paulo',
        unidadeNegocio: 'SP - Sede',
        categoria: 'Categoria 11',
        subcategoria: 'Subcategoria 11',
        assunto: 'Assunto 11',
        descricao: 'Descrição do ticket 11',
        observacao: 'Observação do ticket 11',
        anexo: null,
        autorizacao: 'documento_autorizacao_1010.pdf',
        equipe: 'TI',
    },
    {
        numeroTicket: '1011',
        nomeCompleto: 'Renato Costa',
        status: 'Cancelado',
        abertura: '05/08/2024 13:30:00',
        dataLimite: '',
        matricula: '12356',
        telefone: '11987654332',
        emailSolicitante: 'renato.costa@example.com',
        cargo: 'Gestor de TI',
        areaNegocio: 'TI',
        hub: 'São Paulo',
        unidadeNegocio: 'SP - Sede',
        categoria: 'Categoria 12',
        subcategoria: 'Subcategoria 12',
        assunto: 'Assunto 12',
        descricao: 'Descrição do ticket 12',
        observacao: 'Observação do ticket 12',
        anexo: null,
        autorizacao: 'documento_autorizacao_1011.pdf',
        equipe: 'TI',
    },
    {
        numeroTicket: '1012',
        nomeCompleto: 'Thiago Fernandes',
        status: 'Em Andamento',
        abertura: '04/08/2024 12:10:00',
        dataLimite: '',
        matricula: '12357',
        telefone: '11987654333',
        emailSolicitante: 'thiago.fernandes@example.com',
        cargo: 'Analista de Redes',
        areaNegocio: 'TI',
        hub: 'São Paulo',
        unidadeNegocio: 'SP - Sede',
        categoria: 'Categoria 13',
        subcategoria: 'Subcategoria 13',
        assunto: 'Assunto 13',
        descricao: 'Descrição do ticket 13',
        observacao: 'Observação do ticket 13',
        anexo: null,
        autorizacao: 'documento_autorizacao_1012.pdf',
        equipe: 'TI',
    }
];

export default dadosTickets;
